name: Build

on:
  pull_request:
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: read

jobs:
  build-and-release-draft:
    name: Build & Release draft
    uses: PrestaShop/.github/.github/workflows/build-release.yml@master
